Remove support for linux

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -10,45 +10,18 @@ fi
 # Enable key repeat.  Editors are super awkward without this
 defaults write -g ApplePressAndHoldEnabled -bool false
 
-# Install Salt
-if [[ "$OSTYPE" == "linux-gnu" ]]; then
-  # Linux
-
-  sudo apt-get update
-  sudo apt-get upgrade
-
-  which -s salt-call
-  if [[ $? != 0 ]] ; then
-    echo "Salt not found. Installing it."
-    sudo wget -O - https://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
-    sudo deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2 bionic main
-    sudo apt-get install salt-master
-    sudo apt-get install salt-minion
-    sudo apt-get install salt-ssh
-    sudo apt-get install salt-syndic
-    sudo apt-get install salt-cloud
-    sudo apt-get install salt-api
-    sudo apt-get install python-m2crypto
-  else
-    sudo systemctl restart salt-minion
-  fi
-
-elif [[ "$OSTYPE" == "darwin"* ]]; then
-  # macOS
-  which -s brew
-  if [[ $? != 0 ]] ; then
-    echo "Homebrew not found. Installing it..."
-    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-  else
-    echo "Homebrew found. Updating it..."
-    brew update
-  fi
-
-  brew bundle -v
+# Install Homebrew
+which -s brew
+if [[ $? != 0 ]] ; then
+  echo "Homebrew not found. Installing it..."
+  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 else
-  echo "I don't know how to use this OS"
-  exit 1
+  echo "Homebrew found. Updating it..."
+  brew update
 fi
+
+# Install Dependencies via Brewfile
+brew bundle -v
 
 #
 # Github ssh key setup
